### ISSUE TITLE
event driven

### ISSUE THREAD

**Issue by smartmeter** [martijnboland/MvcNotification#3]
Hi, is there an update for this, I want to do _a server **send/update**_

For e.g. I want to show the user - based on context, you have a new pending request

**Comment by martijnboland** [comment]
There won't be any updates for this. It's just a sample that goes with a blog post (http://blogs.taiga.nl/martijn/2011/05/03/keep-your-users-informed-with-asp-net-mvc/). 

With server send/update, I suspect you're using web sockets/ signalr? In that case I'd probably only leverage mvcNotify.js or perhaps even use a dedicated library like toastr (https://codeseven.github.io/toastr/).
